# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
locale                   : "en-US"
title: "The Cloud Journey"
email: "me@johnalfaro.com"
url                      : "https:/blog.johnalfaro.com" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
description: "a bit of everything around cloud specially around Azure."
twitter_username: j_alex_alfaro
github_username: cerocool1203
repository: "cerocool1203/johnalfaro.github.io"
minimal_mistakes_skin: dark
og_image: /assets/images/splash.jpg
words_per_minute         : 200
logo                     : "/assets/images/cero.jpg"
search: true
atom_feed:
  path                   : "http://feeds.feedburner.com/TheCloudJourney"
# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
# Outputting
permalink: /:categories/:title
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Australia/Melbourne # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
google-site-verification: 'e5HjbhvngEteM7CsvNacmyc1_uIjlZsL01Eu348fMwQ'
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - /blog/backup
# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "John Alfaro"
  avatar : "/assets/images/me.jpg"
  bio    : "Breathing Cloud one day at a time"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto: me@johnalfaro.com"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://blog.johnalfaro.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/j_alex_alfaro"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/cerocool1203"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/john-alex-alfaro/"
    - label: "RSS"
      icon: "fas fa-fw fa-rss-square"
      url: "http://feeds.feedburner.com/TheCloudJourney"
    - label: "Caffeine Support"
      icon: "fas fa-hand-holding-heart"
      url: "https://www.buymeacoffee.com/cerocool"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/j_alex_alfaro"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/cerocool1203"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/john-alex-alfaro/"
    - label: "Caffeine Support"
      icon: "fas fa-hand-holding-heart"
      url: "https://www.buymeacoffee.com/cerocool"


defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: false
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: splash
      image_path: "/assets/images/splash.jpg"
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

compress_html:
  clippings: all
  ignore:
    envs: development

comments:
  provider: "facebook"
  facebook:
    appid: # optional
    num_posts:  5 
    colorscheme: "dark"
